name: Flight Data Scrapbook
description: Statistics, data mining, and machine learning in flight data monitoring
avatar: https://avatars3.githubusercontent.com/u/29257724?v=4&s=460

comments: true

footer-links:
  email: charlie.newey@flightdataservices.com
  flickr:
  github: newey01c
  instagram:
  linkedin:
  rss: yes # just type anything here for a working RSS icon
  twitter:
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/

google_analytics: # e.g. UA-2110908-2
url: https://newey01c.github.io
excerpt_separator: "<!-- more -->"

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

# !! You don't need to change any of the configuration flags below !!
permalink: /:year/:month/:day/:slug/
version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
sass:
  style: :compressed
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed    # Create an Atom feed using the official Jekyll feed gem
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
